export const COMPONENT_INFO = {
  Button: {
    title: "Button",
    description:
      "A button component that supports different variants, sizes, and states. Perfect for triggering actions.",
    label: "Interactive",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Input: {
    title: "Input",
    description:
      "A flexible input component for collecting user data with support for various types and validation states.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Checkbox: {
    title: "Checkbox",
    description: "A control that allows users to select multiple options from a set. Supports indeterminate state.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Select: {
    title: "Select",
    description:
      "A dropdown component for selecting a value from a list of options. Supports search and multiple selection.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Textarea: {
    title: "Textarea",
    description: "A multi-line text input component for longer form content. Supports auto-resize and character count.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Radio Group": {
    title: "Radio Group",
    description: "A set of radio buttons for selecting a single option from multiple choices. Supports custom layouts.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Switch: {
    title: "Switch",
    description: "A toggle switch component for binary choices. Perfect for settings and preferences.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Slider: {
    title: "Slider",
    description: "An input component for selecting a value from a range. Supports single value and range selection.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Date Picker": {
    title: "Date Picker",
    description: "A calendar-based input for selecting dates. Supports date ranges and time selection.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Uploader: {
    title: "Uploader",
    description: "A component for handling file uploads with drag and drop support and progress tracking.",
    label: "Input",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Input OTP": {
    title: "Input OTP",
    description: "A specialized input for one-time passwords and verification codes. Supports auto-focus and paste.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Password: {
    title: "Password",
    description: "A secure input component for password entry with strength indicator and show/hide functionality.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Accordion: {
    title: "Accordion",
    description: "A vertically stacked set of interactive headings that reveal or hide associated sections of content.",
    label: "Interactive",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Alert: {
    title: "Alert",
    description: "A component that displays a brief, important message in a way that attracts the user's attention.",
    label: "Feedback",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Alert Dialog": {
    title: "Alert Dialog",
    description: "A modal dialog that interrupts the user with important content and expects a response.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Aspect Ratio": {
    title: "Aspect Ratio",
    description: "A component that maintains a consistent width-to-height ratio for responsive images and videos.",
    label: "Layout",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Avatar: {
    title: "Avatar",
    description: "A graphical representation of a user or entity with support for images and fallback initials.",
    label: "Data Display",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Badge: {
    title: "Badge",
    description: "A small count and labeling component for displaying status, notifications, or other metadata.",
    label: "Data Display",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Breadcrumb: {
    title: "Breadcrumb",
    description: "A navigation component that shows the current page location within a hierarchical structure.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Calendar: {
    title: "Calendar",
    description: "A date picker component that allows users to select dates from a monthly calendar view.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Card: {
    title: "Card",
    description: "A flexible container for grouping related content and actions. Supports headers, footers, and media.",
    label: "Layout",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Container: {
    title: "Container",
    description: "A versatile container for grouping related components together with optional header and footer.",
    label: "Layout",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
    name: "Container",
    description: "A flexible container to group related components",
    category: "layout",
    icon: "Box", // Usando el icono Box de Lucide
    examples: [
      {
        name: "Default",
        props: {
          showHeader: true,
          showFooter: true,
          headerTitle: "Container Title",
          headerDescription: "This container groups related components together",
          variant: "default",
        },
      },
      {
        name: "With Footer",
        props: {
          showHeader: true,
          showFooter: true,
          headerTitle: "Container with Footer",
          headerDescription: "This container includes a footer section",
          footerContent: "Footer content goes here",
          variant: "shadow",
        },
      },
      {
        name: "Outline",
        props: {
          showHeader: true,
          showFooter: false,
          headerTitle: "Outline Container",
          headerDescription: "A container with outline styling",
          variant: "outline",
        },
      },
    ],
  },
  Carousel: {
    title: "Carousel",
    description: "A slideshow component for cycling through elements like images or slides of content.",
    label: "Data Display",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Collapsible: {
    title: "Collapsible",
    description: "An interactive component that can be expanded or collapsed to reveal or hide content.",
    label: "Interactive",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Combobox: {
    title: "Combobox",
    description: "A combination of a text input and a dropdown list that allows users to filter and select options.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Command: {
    title: "Command",
    description: "A command palette component for searching and executing actions using keyboard commands.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Context Menu": {
    title: "Context Menu",
    description: "A menu that appears on right-click, providing contextual actions for the clicked element.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Data Table": {
    title: "Data Table",
    description:
      "A table component for displaying and interacting with structured data. Supports sorting and filtering.",
    label: "Data Display",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Dialog: {
    title: "Dialog",
    description:
      "A modal window that appears in front of app content to provide critical information or ask for decisions.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Drawer: {
    title: "Drawer",
    description: "A panel that slides in from the edge of the screen. Perfect for navigation or additional content.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Dropdown Menu": {
    title: "Dropdown Menu",
    description: "A button that when clicked reveals a menu of additional options or actions.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Form: {
    title: "Form",
    description: "A collection of form components with built-in validation and error handling capabilities.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Hover Card": {
    title: "Hover Card",
    description: "A popup card that appears when hovering over a trigger element to show additional content.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Menubar: {
    title: "Menu Bar",
    description: "A horizontal menu typically used for top-level navigation and actions in an application.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Navigation Menu": {
    title: "Navigation Menu",
    description: "A responsive navigation component with support for submenus and mega-menus.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Pagination: {
    title: "Pagination",
    description: "A component for splitting up content into multiple pages and navigating between them.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Popover: {
    title: "Popover",
    description: "A floating element that displays additional content when a trigger element is clicked.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Progress: {
    title: "Progress",
    description: "A progress indicator component that shows the completion status of a task or process.",
    label: "Feedback",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Scroll Area": {
    title: "Scroll Area",
    description: "A custom scrollable container with consistent cross-browser styling.",
    label: "Layout",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Separator: {
    title: "Separator",
    description: "A visual divider between content. Supports horizontal and vertical orientations.",
    label: "Layout",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Sheet: {
    title: "Sheet",
    description: "A modal dialog that slides in from the edge of the screen. Similar to a drawer but more flexible.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Skeleton: {
    title: "Skeleton",
    description: "A placeholder loading state for content that is yet to be loaded.",
    label: "Feedback",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Tabs: {
    title: "Tabs",
    description: "A set of layered sections of content that display one panel at a time.",
    label: "Navigation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Tooltip: {
    title: "Tooltip",
    description:
      "A popup that displays information related to an element when it receives keyboard focus or is hovered.",
    label: "Overlay",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Toggle: {
    title: "Toggle",
    description: "A two-state button that can be either on or off. Similar to a switch but with button styling.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  Toast: {
    title: "Toast",
    description: "A brief notification that appears temporarily and automatically dismisses itself.",
    label: "Feedback",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
  "Toggle Group": {
    title: "Toggle Group",
    description: "A set of two-state buttons that can be toggled on or off. Supports single and multiple selection.",
    label: "Form",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HQvSRDhH3XFQ5NCjBtijy9xiJkXW7E.png",
  },
}
